# Since our default folder structure is task/seed/algo/experiment_name/datetime,
# we have algo/experiment_name for each task/algo combo

algo_dir_names = ['multi-sqil', 'multi-disc', 'multi-rce', 'sqil', 'dac', 'rce']

main_performance = {
    'door-human-v0-dp': {
        'multi-sqil':        "multi-sqil/mar19",
        'multi-disc':        "multi-disc/mar19",
        'sqil':              "sqil/mar19",
        'rce':               "rce/mar19",
        'rce_orig':          "rce_theirs/dummy",
        'sqil_theirs':       "sqil_theirs/dummy",
        'disc':              "disc/apr2",
        'multi-rce':         "multi-rce/apr2",
        'sqil_theirs_nstepoff': "sqil_theirs_nstepoff/dummy",
        'multi-sqil-no-vp':          "multi-sqil/apr4_noqovermax",
        'sqil-no-vp':        "sqil/apr4_noqovermax",
    },
    'hammer-human-v0-dp': {
        'multi-sqil':        "multi-sqil/mar19",
        'multi-disc':        "multi-disc/mar19",
        'sqil':              "sqil/mar19",
        'rce':               "rce/mar19",
        'rce_orig':          "rce_theirs/dummy",
        'sqil_theirs':       "sqil_theirs/dummy",
        'disc':              "disc/apr2",
        'multi-rce':         "multi-rce/apr2",
        'sqil_theirs_nstepoff': "sqil_theirs_nstepoff/dummy",
        'multi-sqil-no-vp':          "multi-sqil/apr4_noqovermax",
        'sqil-no-vp':        "sqil/apr4_noqovermax",
    },
    'relocate-human-v0-najp-dp': {
        # 'multi-sqil':        "multi-sqil/mar19",
        'multi-sqil':        "multi-sqil/mar21",
        'multi-disc':        "multi-disc/mar21",
        'sqil':              "sqil/mar21",
        'rce':               "rce/mar21",
        'rce_orig':          "rce_theirs/dummy",
        'sqil_theirs':       "sqil_theirs/dummy",
        'disc':              "disc/apr4",
        'multi-rce':         "multi-rce/apr2",
        'sqil_theirs_nstepoff': "sqil_theirs_nstepoff/dummy",
        'multi-sqil-no-vp':          "multi-sqil/apr4_noqovermax",
        'sqil-no-vp':        "sqil/apr4_noqovermax",
    },
    'door-human-v0': {
        'multi-sqil':        "multi-sqil/mar19",
        'multi-disc':        "multi-disc/mar19",
        'sqil':              "sqil/mar19",
        'rce':               "rce/mar19",
        'rce_orig':          "rce_theirs/mar23",
        'sqil_theirs':       "sqil_theirs/mar27",
        'disc':              "disc/mar31",
        'multi-rce':         "multi-rce/mar31",
        'sqil_theirs_nstepoff': "sqil_theirs_nstepoff/apr1",
        'multi-sqil-no-vp':          "multi-sqil/apr4_noqovermax",
        'sqil-no-vp':        "sqil/apr4_noqovermax",
    },
    'hammer-human-v0': {
        'multi-sqil':        "multi-sqil/mar19",
        'multi-disc':        "multi-disc/mar19",
        'sqil':              "sqil/mar19",
        'rce':               "rce/mar19",
        'rce_orig':          "rce_theirs/mar23",
        'sqil_theirs':       "sqil_theirs/mar27",
        'disc':              "disc/mar31",
        'multi-rce':         "multi-rce/mar31",
        'sqil_theirs_nstepoff': "sqil_theirs_nstepoff/apr1",
        'multi-sqil-no-vp':          "multi-sqil/apr4_noqovermax",
        'sqil-no-vp':        "sqil/apr4_noqovermax",
    },
    'relocate-human-v0': {
        # 'multi-sqil':        "multi-sqil/mar19",
        'multi-sqil':        "multi-sqil/mar21",
        'multi-disc':        "multi-disc/mar21",
        'sqil':              "sqil/mar19",
        'rce':               "rce/mar19",
        'rce_orig':          "rce_theirs/mar23",
        'sqil_theirs':       "sqil_theirs/mar27",
        'disc':              "disc/dummy",
        'multi-rce':         "multi-rce/apr28",
        'sqil_theirs_nstepoff': "sqil_theirs_nstepoff/dummy",
        'multi-sqil-no-vp':          "multi-sqil/apr26_noqovermax",
        'sqil-no-vp':        "sqil/apr26_noqovermax",
    },
}
